env:
  global:
    # COVERALLS_REPO_TOKEN to send coverage report to coveralls
    secure: "FDDw9/hS6wXPBvZTosFuzcRmfL3N5xGAzufisfxacpyX4jQNVHCpkwrWR/2Opw4n2Z1gFzq5QzPEsHKvNSwGTG+VE5qZYaZX++ZwZvq5AVKf9wZtw4xoxjPoHJ2h2HP5nyP3C8Qopf/r7+LEy3ahj3bsFaIfW6K5HAoN6TyOM6o3icxl04UDNBMGpCUTjE8q5GZ5Ozmqktm4pfpJ6cQR3n/45b1p+xGl0jvgULjeP430WJhTaILp8ukjnbsrD1Ii2aJOVVCpBOISLsiE08Ch4IFtDRGp6WZa5Kh/Uv7wnjtjqLczPgQ1RKNo2Kg9+11gmt+MkycLC38oI7UjxeaPRBrTEJ8NEaQbEHRKvJp5NE4v1qDnmd21tlNBUaS9h8FgB/zPEpO7QSoaKeiQjtIQ1LNM68fK1ZZp6t2C+4oJqyNnv3zoB1vAmLVN5uaGjFglNHJP45i7x2dC7rlF+4cTeh3gcY1swvrhkmEVgEyIX2c2xJDbqLRKHz7KvQSLp5zfNpC+RWyQzwDEODufr1JVLbYV7zseaGyeFItQltglekIwgg8DSQbeCGhn6B6V3sNjIpoMuLNyZBkParvzs+EioPEBrOjTFE9NLtsAofhi50omhzLim4UGMp23WChUohKhhJttsV47wNLyI+V3bb5uI8vcBqiYElHOhLbJAHYwpAA="
    # DOCKERHUB_TRIGGER_TOKEN to trigger a build on dockerhub
    secure: "lnArNdOsfllmA6hLcN/mYcdWels3bv20Kh1G+jjaXxAOQFFZRbk9dI48WoGDXk4/PGSIKuC5qnPz5rL97yyB7V2EXHsAMJLnH9ldHCeQIoXwnnPfuQyjtix/D8bTTuPgvkGHA+yy4/msR8t35uWKWnn+6dTeG7yWFF3WAxZuq/tHHbDZ6kILrLN6EGJ3TbFnVoiui5OAwPVsaKHc2TCJ0+zMPEE5E8EJ5ZkRG0o2Z7LvuerpWdRujxn2aaEdwhlS1xyXTSJXSkNhOam9HtYhPcvnG+i8aheVdpn950qFFBYQkDTUvyuHCkloLWYMD7jgKAqWmKy/xs1Ih9XOuVeGeKtUyu3VuBPQ2W0+gz8AzYkftf4BMfRmfO5TteP9uDDV45phP/0J+wHydozs7CcIR1IkKd/wMxiv86n8o5n/G7rUdfLuUUfpXbF4Mq3Cpq7ynxfKRrPFmCNHBOvupvv9ZDLtJR13PVKiQlRPaPqHfSts5WyJad4r4JxA0DzZGyk/HTCLWN8aHJtow4kAaE7TJlmPgRU8LGmQTVkfNBhHe/HqguVv0BmUVVUUsYhDytvsSBIcpzVDGrV3quDZ7ZHsqzSgkzZv/GU25jQbJh5I05fh1yHmOTrvz1eMIHSoF6pmnRK7pFxcaLE2EdZWlB+Cwvxpc8yncNIkO8V6iHJNhYQ="

branches:
  only:
    - master

language: node_js
node_js:
  - '4'

sudo: required
services:
  - docker

install:
  - npm install

script:
  - make lint
  - make test
  - make check-coverage
  - make test-dist

after_script:
  - docker run -p 3111:3111 -e COVERALLS_SERVICE_NAME=travis-ci -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" -it --rm --name flux-templating-test -v "$PWD":/usr/src/app node:4.2 sh -c "cat /usr/src/app/coverage/lcov.info | /usr/src/app/node_modules/.bin/coveralls"

after_success:
  - curl -XPOST https://registry.hub.docker.com/u/albanm/flux-templating/trigger/"$DOCKERHUB_TRIGGER_TOKEN"/
