branches:
  only:
    - master

language: node_js
node_js:
  - '4'

sudo: required
services:
  - docker

install:
  - npm install
  - npm run build

script:
  - npm test
  - npm run test-dist
  - npm run lint
