env:
  global:
    # COVERALLS_REPO_TOKEN to send coverage report to coveralls
    secure: "P1/7B7QWSt44xFZXdWnDG47dA1zSsEgvToMcLmWf19ElfTGp+WkoI5aTSU0EkrIGuSu/0OW7fnoSsnzIt430DrN6KVwVm7uR439C2YLgzgbAhNLhCbkZMXqqhpEGwm27lpIOImneyKrunBgeVmr0UVHLA9MepREXdl643CbarHWjkq5gBt3yPTISwuj+vuark9Z3DPqeABx6LPOwBvHtOY2qeTa1/BqZk8KbJ+qbdNBh539pAzN0UG7EEcR/Cm29Q2upFUwDMJGwHGtvjsY7T4HSoCvgI9agrWrjjPM1ZteeVPS0pzTLnxKNAbM0pD/E/kgOfG2lH/a2g7suONxeEcLOIPoAX/T9dQov40Z+geEAULDDKJN0xYKpF0CF14M+WisGVJPIEqtxTd4tjrYV8B9I82QYJOidCenb35ZPF5Ps/j5NoPdidU6OyszUgwyc7roEwB6QxgO07d7cOjNabqsrD0gXWMGLN15555n7aqMxlyrzkSdQvVT5jrXnnbldK3HKRi/KVMvy6RATIStZsrk4rKRcSPUJ0ILnpwSxBl7SXUgl47U7s+X+AyJ1AiJxwedTN+p93rMlb9rxXWUP4oX+wx/OHHCIs+JcVyfWjtUdxIZpltChcma3USecod+dPP5GJGRZRFccLlFoGx3eaCdCWGLrwQusRhybIiTGm6U="
    # DOCKERHUB_TRIGGER_TOKEN to trigger a build on dockerhub
    secure: "Em2s/k0KtZw9p+OXmOnX+wT5ubmNS9grAin+vR5sP+2gbWPJbRw2rYyv1WQMBBcphQK3NNeG7Bb3rd7QkEjZLMlrnyVCsC8fMLSpMHm3Iq9SnifAxF5HgxlhN/GxVIj52iIVakvc+1k1vea/t4EU8JooF3m0hMNfORyvdzDrPvZnjqTVOWG4YFLB9N8ETDxLXA6GWMXnwdMKrysV8pygzjt5s5KV38/9p+728Qt+2UiYw3uYGmRFn3s/fSs4BFbvofPp21BI3/BRnqYIvXD5OELCj7oVcRWGPELT0PMjrvBdfNP6Aiuy5ig+bLJN91u7p3qLig1/TNYosmdXPhxQ9gEpafE+HRSkEfm8Ac2HGE0x/XU9KzZZ4t4If1P1G1lNtL/QWtyxHb3euTmDZOK1KURtVbY+NremYpvEhPYNBLnfGKTgwYYD4G7eTySujMGqYR2gAY7GBaNrVzv6J68hcnAQ8WQ9OY3SKhC7HjMISyq9/m+3yUX3xooNvJnqoR3L4YDhrFZnP0ArOIAwpeV+q7Am7nqZMKq0EL5hCd6n7r9j5/DWzdTrpNgNJR+U6ZEtPOgYvDKlITKo+ginQtRqgL9ighCx75LrdTUp3jrSynAhZZUy6wQZ80GXUUbYdWN79jF0z5jFWHBjEAGLPm49jgySX4omIISJmvOxvaeqYGQ="

branches:
  only:
    - master

language: node_js
node_js:
  - '4'

sudo: required
services:
  - docker

install:
  - npm install

script:
  - make lint
  - make test
  - make check-coverage
  - make test-dist

after_script:
  - docker run -p 3111:3111 -e COVERALLS_SERVICE_NAME=travis-ci -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" -it --rm --name flux-templating-test -v "$PWD":/usr/src/app fluxtemplating_flux-templating_1 sh -c "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

after_success:
  - curl -XPOST https://registry.hub.docker.com/u/albanm/flux-templating/trigger/"$DOCKERHUB_TRIGGER_TOKEN"/
