flux-templating:
  image: node:4.2
  working_dir: /usr/src/app
  command: ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- test/server.js test/integration/*.js
  volumes:
    - .:/usr/src/app
    - ./coverage:/usr/src/app/coverage
  ports:
    - 3111:3111
  links:
    - unoconv-worker:unoconv-worker
    - phantomjs-worker:phantomjs-worker

unoconv-worker:
  image: fluxs/unoconv-worker

phantomjs-worker:
  image: fluxs/phantomjs-worker
