port: 3111
templatesPath: ../../resources/
log:
  transports:
    console:
      type: Console
      level: debug
      colorize: true
      prettyPrint: true
  loggers:
    flux-templating:
      - console
